name: tcc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/


